/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hanna Nathania
 */
public class DashboardAdmin extends javax.swing.JFrame {
    BarangController cb = new BarangController();
    TransaksiController ct = new TransaksiController();
    PembeliController cp = new PembeliController();
    String session;
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        jLabel14.setText("");
        showBarang();
    }
    
    private void hideButton(){
        hapus.setVisible(false);
        update.setVisible(false);
        tambah.setVisible(false);
    }
    
    private void showButton(){
        hapus.setVisible(true);
        update.setVisible(true);
        tambah.setVisible(true); 
    }
    
    private void hideField(){
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        combobox.setVisible(false);
    }
    
    private void showField(){
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
    }    
    
    private void clearField(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    } 
    
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        model.setRowCount(0);
    }
    
    private void hideLabel(){
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
        jLabel6.setText("");
    }
    
    private void showPembeli(){
        tabel.setVisible(true);
        clearField();
        List <Pembeli> list = cp.getAllPembeli(); 
        Object[][] objectpem = new Object[list.size()][5]; 
        int i =0 ; 
        for (Pembeli pem : list) { 
            objectpem[i][0] = pem.getUsername();
            objectpem[i][1] = pem.getNama();
            objectpem[i][2] = pem.getEmail();
            objectpem[i][3] = pem.getAlamat();
            objectpem[i][4] = pem.getPassword();
            i++; //increment
        }
        tabel.setModel(new javax.swing.table.DefaultTableModel(objectpem, new  String[] {"Username", "Nama", "Email", "Alamat", "Password"}));
        tabel.getColumnModel().getColumn(0).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(1).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(2).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(3).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(4).setPreferredWidth(5);
        tabel.setDefaultEditor(Object.class, null);
    }
    
    private void showBarang(){
        tabel.setVisible(true);
        clearField();
        List <Barang> list = cb.getAllBarang(); 
        Object[][] objectbrg = new Object[list.size()][5]; 
        int i =0 ; 
        for (Barang brg : list) { 
            objectbrg[i][0] = brg.getId_barang();
            objectbrg[i][1] = brg.getNama();
            objectbrg[i][2] = brg.getKategori();
            objectbrg[i][3] = brg.getHarga();
            objectbrg[i][4] = brg.getStok();
            i++; //increment
        }
        tabel.setModel(new javax.swing.table.DefaultTableModel(objectbrg, new  String[] {"ID", "Nama", "Kategori", "Harga", "Stok"}));
        tabel.getColumnModel().getColumn(0).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(1).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(2).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(3).setPreferredWidth(5);
        tabel.getColumnModel().getColumn(4).setPreferredWidth(5);
        tabel.setDefaultEditor(Object.class, null);
        
        jLabel10.setText("ID Barang :");
        jLabel11.setText("Nama Barang :");
        jLabel12.setText("Kategori Barang :");
        jLabel13.setText("Harga Barang :");
        jLabel6.setText("Stok Barang :");
        
        session = "barang";
        showButton();
        showField();
        jTextField3.setVisible(false);
        combobox.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        update = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tambah = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        hapus = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mamania Bakery");
        setPreferredSize(new java.awt.Dimension(1021, 585));
        setResizable(false);
        setSize(new java.awt.Dimension(1021, 585));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minilogo.jpg"))); // NOI18N
        jLabel1.setText("MAMANIA BAKERY");

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Barang");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Pembeli");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Logout");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Transaksi");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        update.setBackground(new java.awt.Color(255, 204, 204));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Update");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        tambah.setBackground(new java.awt.Color(255, 204, 204));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Tambah");

        javax.swing.GroupLayout tambahLayout = new javax.swing.GroupLayout(tambah);
        tambah.setLayout(tambahLayout);
        tambahLayout.setHorizontalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        tambahLayout.setVerticalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        hapus.setBackground(new java.awt.Color(255, 204, 204));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Hapus");

        javax.swing.GroupLayout hapusLayout = new javax.swing.GroupLayout(hapus);
        hapus.setLayout(hapusLayout);
        hapusLayout.setHorizontalGroup(
            hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        hapusLayout.setVerticalGroup(
            hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("");

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Roti", "Round Cake", "Pastry", "Kue Basah", "Parcel" }));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        showBarang();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        showPembeli();
        
        jLabel10.setText("Username :");
        jLabel11.setText("Nama Lengkap :");
        jLabel12.setText("Email :");
        jLabel13.setText("Alamat :");
        jLabel6.setText("Password :");
        
        session = "pembeli";
        showButton();
        showField();
        combobox.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        tabel.setVisible(true);
        clearField();
        List <Transaksi> list = ct.getAllTransaksi(); 
        Object[][] objecttr = new Object[list.size()][8]; 
        int i =0 ; 
        int pendapatan =0;
        int barangterjual = 0;
        for (Transaksi trans : list) { 
            objecttr[i][0] = trans.getId_transaksi();
            objecttr[i][1] = trans.getId_barang();
            objecttr[i][2] = trans.getUsername();
            objecttr[i][3] = trans.getKategoribarang();
            objecttr[i][4] = trans.getQty();
            objecttr[i][5] = trans.getHargabarang();
            objecttr[i][6] = trans.getWaktutransaksi();
            objecttr[i][7] = trans.getTotalharga();
            
            pendapatan += Integer.parseInt(objecttr[i][7].toString()); 
            barangterjual += Integer.parseInt(objecttr[i][4].toString());  
            i++; //increment
             
        }
        tabel.setModel(new javax.swing.table.DefaultTableModel(objecttr, new  String[] {"ID Transaksi", 
                                                                                           "ID Barang",
                                                                                           "Username", 
                                                                                           "Katogori Barang", 
                                                                                           "Qty",
                                                                                           "Harga Barang",
                                                                                           "Waktu Transaksi",
                                                                                           "Total Harga"}));
        tabel.getColumnModel().getColumn(0).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(1).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(2).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(3).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(4).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(5).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(6).setPreferredWidth(15);
        tabel.getColumnModel().getColumn(7).setPreferredWidth(15);
        tabel.setDefaultEditor(Object.class, null);
        
        session = "transaksi";
        hideField();
        hideLabel();
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField1.setText(Integer.toString(barangterjual));
        jTextField2.setText(Integer.toString(pendapatan));
        jLabel10.setText("Total Barang Terjual :");
        jLabel11.setText("Total Pendapatan :");
        
        hideButton();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        
        if (session == "barang"){
            String id_barang,namabarang,kategoribarang;
            int harga,stok;

            int row = tabel.getSelectedRow();
            id_barang = tabel.getValueAt(row, 0).toString();
            namabarang = tabel.getValueAt(row, 1).toString();
            kategoribarang = tabel.getValueAt(row, 2).toString();
            harga = Integer.parseInt(tabel.getValueAt(row, 3).toString());
            stok = Integer.parseInt(tabel.getValueAt(row, 4).toString());

            jTextField1.setText(id_barang);
            jTextField2.setText(namabarang);
            combobox.setSelectedItem(kategoribarang);
            jTextField4.setText(Integer.toString(harga));
            jTextField5.setText(Integer.toString(stok)); 
        } else if (session == "pembeli"){
            String username, nama,email, alamat,password;
            
            int row = tabel.getSelectedRow();
            username = tabel.getValueAt(row, 0).toString();
            nama = tabel.getValueAt(row, 1).toString();
            email = tabel.getValueAt(row, 2).toString();
            alamat = tabel.getValueAt(row, 3).toString();
            password = tabel.getValueAt(row, 4).toString();

            jTextField1.setText(username);
            jTextField2.setText(nama);
            jTextField3.setText(email);
            jTextField4.setText(alamat);
            jTextField5.setText(password);    
        } 
        

    }//GEN-LAST:event_tabelMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        try {
            if (session =="pembeli"){
                String username, nama, email, alamat, password;

                int row = tabel.getSelectedRow();
                username = jTextField1.getText();
                nama = jTextField2.getText();
                email = jTextField3.getText();
                alamat = jTextField4.getText();
                password = jTextField5.getText();   

                Pembeli ubahpembeli = new Pembeli(username,nama,email,alamat,password);

                int hasil = cp.updatePembeli(ubahpembeli);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showPembeli();
            } else if (session == "barang"){
                String id_barang,namabarang,kategoribarang;
                int harga,stok;

                int row = tabel.getSelectedRow();
                id_barang = jTextField1.getText();
                namabarang = jTextField2.getText();
                kategoribarang = (String) combobox.getSelectedItem();
                harga = Integer.parseInt(jTextField4.getText());
                stok = Integer.parseInt(jTextField5.getText());

                Barang ubahbarang = new Barang(id_barang,namabarang,kategoribarang,harga,stok);

                int hasil = cb.updateBarang(ubahbarang);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showBarang();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
        }
    }//GEN-LAST:event_updateMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        try {
            if (session =="pembeli"){
                String username, nama, email, alamat, password;

                int row = tabel.getSelectedRow();
                username = jTextField1.getText();
                nama = jTextField2.getText();
                email = jTextField3.getText();
                alamat = jTextField4.getText();
                password = jTextField5.getText();   

                Pembeli hapuspembeli = new Pembeli(username,nama,email,alamat,password);

                int hasil = cp.deletePembeli(hapuspembeli);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showPembeli();
            } else if (session == "barang"){
                String id_barang,namabarang,kategoribarang;
                int harga,stok;

                int row = tabel.getSelectedRow();
                id_barang = jTextField1.getText();
                namabarang = jTextField2.getText();
                kategoribarang = (String) combobox.getSelectedItem();
                harga = Integer.parseInt(jTextField4.getText());
                stok = Integer.parseInt(jTextField5.getText());

                Barang hapusbarang = new Barang(id_barang,namabarang,kategoribarang,harga,stok);

                int hasil = cb.deleteBarang(hapusbarang);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showBarang();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        // TODO add your handling code here:
        try {
            if (session =="pembeli"){
                String username, nama, email, alamat, password;

                username = jTextField1.getText();
                nama = jTextField2.getText();
                email = jTextField3.getText();
                alamat = jTextField4.getText();
                password = jTextField5.getText();   

                Pembeli pembeli = new Pembeli(username,nama,email,alamat,password);

                int hasil = cp.createPembeli(pembeli);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showPembeli();
            } else if (session == "barang"){
                String id_barang,namabarang,kategoribarang;
                int harga,stok;

                id_barang = jTextField1.getText();
                namabarang = jTextField2.getText();
                kategoribarang = (String) combobox.getSelectedItem();
                harga = Integer.parseInt(jTextField4.getText());
                stok = Integer.parseInt(jTextField5.getText());

                Barang barang = new Barang(id_barang,namabarang,kategoribarang,harga,stok);

                int hasil = cb.createBarang(barang);
                if (hasil == -1){
                    JOptionPane.showMessageDialog(null,"Gagal memperbaharui data");
                } else {
                    JOptionPane.showMessageDialog(null,"Berhasil memperbaharui data");
                }
                showBarang();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
        }
    }//GEN-LAST:event_tambahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JPanel hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabel;
    private javax.swing.JPanel tambah;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
